server:
  port: 8081
spring:
  application:
    name: student-rest-service
  profiles:
    include:
    - complex

configuration:
  property:
    value: Hello from Property file, modified at 16:09 21/04/2021, v1.1